baseURL = "https://example.com"
languageCode = "en-us"
title = "Archie-mod"
theme="archie-mod"
copyright = "© lipidex"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/lipidex)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/lipidex"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/pierpaolo-agamennone/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/pierpaoloaga/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
